
let Test = [
    GroupChat {
      groupMetadata: {
        id: [Object],
        creation: 1669171485,
        owner: [Object],
        subject: 'Hbj-monitor',
        subjectTime: 1671096803,
        descTime: 0,
        restrict: false,
        announce: false,
        noFrequentlyForwarded: false,
        ephemeralDuration: 0,
        membershipApprovalMode: false,
        size: 1,
        support: false,
        suspended: false,
        terminated: false,
        uniqueShortNameMap: {},
        isParentGroup: false,
        isParentGroupClosed: false,
        defaultSubgroup: false,
        lastActivityTimestamp: 0,
        lastSeenActivityTimestamp: 0,
        incognito: false,
        participants: [Array],
        pendingParticipants: [],
        pastParticipants: [Array],
        membershipApprovalRequests: []
      },
      id: {
        server: 'g.us',
        user: '120363047248625997',
        _serialized: '120363047248625997@g.us'
      },
      name: 'Hbj-monitor',
      isGroup: true,
      isReadOnly: false,
      unreadCount: 0,
      timestamp: 1672110150,
      archived: undefined,
      pinned: false,
      isMuted: false,
      muteExpiration: 0
    },
    GroupChat {
      groupMetadata: {
        id: [Object],
        creation: 1671788021,
        owner: [Object],
        subject: 'pretest',
        subjectTime: 1671788021,
        descTime: 0,
        restrict: false,
        announce: false,
        noFrequentlyForwarded: false,
        ephemeralDuration: 0,
        membershipApprovalMode: false,
        size: 2,
        support: false,
        suspended: false,
        terminated: false,
        uniqueShortNameMap: {},
        isParentGroup: false,
        isParentGroupClosed: false,
        defaultSubgroup: false,
        lastActivityTimestamp: 0,
        lastSeenActivityTimestamp: 0,
        incognito: false,
        participants: [Array],
        pendingParticipants: [],
        pastParticipants: [Array],
        membershipApprovalRequests: []
      },
      id: {
        server: 'g.us',
        user: '120363047959590471',
        _serialized: '120363047959590471@g.us'
      },
      name: 'pretest',
      isGroup: true,
      isReadOnly: false,
      unreadCount: 0,
      timestamp: 1672045438,
      archived: undefined,
      pinned: false,
      isMuted: false,
      muteExpiration: 0
    },
    GroupChat {
      groupMetadata: {
        id: [Object],
        creation: 1671684487,
        owner: [Object],
        subject: 'Test',
        subjectTime: 1671684487,
        descTime: 0,
        restrict: false,
        announce: false,
        noFrequentlyForwarded: false,
        ephemeralDuration: 0,
        membershipApprovalMode: false,
        size: 1,
        support: false,
        suspended: false,
        terminated: false,
        uniqueShortNameMap: {},
        isParentGroup: false,
        isParentGroupClosed: false,
        defaultSubgroup: false,
        lastActivityTimestamp: 0,
        lastSeenActivityTimestamp: 0,
        incognito: false,
        participants: [Array],
        pendingParticipants: [],
        pastParticipants: [Array],
        membershipApprovalRequests: []
      },
      id: {
        server: 'g.us',
        user: '120363029537423607',
        _serialized: '120363029537423607@g.us'
      },
      name: 'Test',
      isGroup: true,
      isReadOnly: false,
      unreadCount: 0,
      timestamp: 1672026445,
      archived: undefined,
      pinned: false,
      isMuted: false,
      muteExpiration: 0
    }

  ]
  console.log(test)